"""Deterministic OpenAPI contract and TypeScript SDK lifecycle."""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Annotated, Any

import typer

sdk_app = typer.Typer(help="Generate and verify typed clients from a FastAPI contract.")


def _contract(project: Path) -> dict[str, Any]:
    """Load a project's OpenAPI document in an isolated subprocess."""
    code = "import json; from app.main import app; print(json.dumps(app.openapi(), sort_keys=True))"
    environment = dict(os.environ)
    environment["PYTHONPATH"] = os.pathsep.join(
        filter(None, [str(project), os.environ.get("PYTHONPATH", "")])
    )
    try:
        result = subprocess.run(
            [sys.executable, "-c", code], cwd=project, env=environment,
            capture_output=True, text=True, timeout=15, check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError("Application contract import timed out") from exc
    if result.returncode:
        raise RuntimeError("Application contract import failed")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Application produced an invalid OpenAPI contract") from exc


def _canonical(contract: dict[str, Any]) -> bytes:
    """Serialize an OpenAPI document deterministically for hashing."""
    return (json.dumps(contract, sort_keys=True, separators=(",", ":")) + "\n").encode()


def _method_name(method: str, path: str) -> str:
    """Create a stable camel-case TypeScript operation name."""
    parts = [part for part in path.split("/") if part and not part.startswith("{")]
    noun = parts[-1] if parts else "root"
    singular = noun[:-1] if noun.endswith("s") else noun
    verb = {"post": "create", "put": "replace", "patch": "update", "delete": "delete"}.get(method, "get")
    target = singular if method != "get" or "{" in path else noun
    words = re.split(r"[^A-Za-z0-9]+", verb + " " + target)
    return words[0].lower() + "".join(word.title() for word in words[1:] if word)


def _typescript(contract: dict[str, Any], digest: str) -> str:
    """Render a dependency-free TypeScript fetch client from OpenAPI paths."""
    methods: list[str] = []
    supported = {"get", "post", "put", "patch", "delete"}
    for path, operations in sorted(contract.get("paths", {}).items()):
        for method, operation in sorted(operations.items()):
            if method not in supported:
                continue
            name = _method_name(method, path)
            path_params = re.findall(r"{([^}]+)}", path)
            params = [f"{item}: string | number" for item in path_params]
            has_body = "requestBody" in operation
            if has_body:
                params.append("body: unknown")
            params.append("options: RequestInit = {}")
            expression = path
            for item in path_params:
                expression = expression.replace("{" + item + "}", "${encodeURIComponent(String(" + item + "))}")
            body = "\n      body: JSON.stringify(body)," if has_body else ""
            content_type = "\n      headers: { 'content-type': 'application/json', ...options.headers }," if has_body else ""
            methods.append(
                f"  async {name}({', '.join(params)}): Promise<unknown> {{\n"
                f"    return this.request(`{expression}`, {{ ...options, method: '{method.upper()}',{content_type}{body} }});\n"
                "  }"
            )
    joined = "\n\n".join(methods)
    return f'''/* Generated by SmartVintaAwesomeKit. OpenAPI SHA-256: {digest} */
export class ApiError extends Error {{
  constructor(public readonly status: number, public readonly payload: unknown) {{
    super(`API request failed with status ${{status}}`);
  }}
}}

export class ApiClient {{
  constructor(private readonly baseUrl: string, private readonly fetcher: typeof fetch = fetch) {{}}

  private async request(path: string, init: RequestInit): Promise<unknown> {{
    const response = await this.fetcher(`${{this.baseUrl}}${{path}}`, init);
    const text = await response.text();
    const payload: unknown = text ? JSON.parse(text) : null;
    if (!response.ok) throw new ApiError(response.status, payload);
    return payload;
  }}

{joined}
}}
'''


def _paths(project: Path) -> tuple[Path, Path, Path]:
    directory = project / "sdk" / "typescript"
    return directory / "client.ts", directory / "openapi.json", directory / "openapi-lock.json"


@sdk_app.command("generate")
def generate(
    project: Annotated[Path, typer.Option("--project")] = Path("."),
    dry_run: Annotated[bool, typer.Option("--dry-run")] = False,
    json_output: Annotated[bool, typer.Option("--json")] = False,
) -> None:
    """Generate a deterministic TypeScript client and locked OpenAPI contract."""
    project = project.resolve()
    try:
        contract = _contract(project)
    except RuntimeError:
        payload = {"status": "error", "code": "openapi_import_failed",
                   "remediation": "Run the application locally and inspect startup logs"}
        typer.echo(json.dumps(payload, indent=2) if json_output else payload["remediation"])
        raise typer.Exit(1) from None
    canonical = _canonical(contract)
    digest = hashlib.sha256(canonical).hexdigest()
    client_path, contract_path, lock_path = _paths(project)
    payload = {"status": "preview" if dry_run else "generated", "dry_run": dry_run,
               "openapi_sha256": digest,
               "files": [str(path.relative_to(project)) for path in (client_path, contract_path, lock_path)]}
    if not dry_run:
        client_path.parent.mkdir(parents=True, exist_ok=True)
        client_path.write_text(_typescript(contract, digest), encoding="utf-8")
        contract_path.write_bytes(canonical)
        lock_path.write_text(json.dumps({"schema_version": 1, "openapi_sha256": digest,
                                         "generator": "smartvintaawesomekit"}, indent=2) + "\n",
                             encoding="utf-8")
    typer.echo(json.dumps(payload, indent=2) if json_output else f"SDK {payload['status']}: {digest}")


@sdk_app.command("check")
def check(
    project: Annotated[Path, typer.Option("--project")] = Path("."),
    json_output: Annotated[bool, typer.Option("--json")] = False,
) -> None:
    """Fail when the generated SDK does not match the current OpenAPI contract."""
    project = project.resolve()
    _client, _contract_path, lock_path = _paths(project)
    try:
        current = hashlib.sha256(_canonical(_contract(project))).hexdigest()
        locked = json.loads(lock_path.read_text(encoding="utf-8")).get("openapi_sha256")
    except (RuntimeError, OSError, json.JSONDecodeError):
        current, locked = "unavailable", None
    fresh = current == locked and locked is not None
    payload = {"status": "fresh" if fresh else "stale", "openapi_sha256": current,
               "locked_sha256": locked,
               "remediation": "none" if fresh else "Run smartvintaawesomekit sdk generate --project ."}
    typer.echo(json.dumps(payload, indent=2) if json_output else f"SDK contract: {payload['status']}")
    if not fresh:
        raise typer.Exit(1)


__all__ = ["check", "generate", "sdk_app"]
